# Copyright 2013 The Android Open Source Project
# Modifications Copyright 2013 The OmniROM Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# blob(s) necessary for Hammerhead hardware
PRODUCT_COPY_FILES := \
    vendor/lge/hammerhead/proprietary/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/lge/hammerhead/proprietary/LMspeed_508.emd:system/vendor/media/PFFprec_600.emd \
    vendor/lge/hammerhead/proprietary/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/lge/hammerhead/proprietary/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/lge/hammerhead/proprietary/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/lge/hammerhead/proprietary/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/lge/hammerhead/proprietary/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/lge/hammerhead/proprietary/OmaDmclient.apk:system/app/OmaDmclient.apk \
    vendor/lge/hammerhead/proprietary/DxHDCP.cfg:system/etc/DxHDCP.cfg \
    vendor/lge/hammerhead/proprietary/bridgemgrd:system/bin/bridgemgrd \
    vendor/lge/hammerhead/proprietary/diag_klog:system/bin/diag_klog \
    vendor/lge/hammerhead/proprietary/diag_mdlog:system/bin/diag_mdlog \
    vendor/lge/hammerhead/proprietary/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/lge/hammerhead/proprietary/irsc_util:system/bin/irsc_util \
    vendor/lge/hammerhead/proprietary/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/lge/hammerhead/proprietary/mpdecision:system/bin/mpdecision \
    vendor/lge/hammerhead/proprietary/netmgrd:system/bin/netmgrd \
    vendor/lge/hammerhead/proprietary/nl_listener:system/bin/nl_listener \
    vendor/lge/hammerhead/proprietary/port-bridge:system/bin/port-bridge \
    vendor/lge/hammerhead/proprietary/qmuxd:system/bin/qmuxd \
    vendor/lge/hammerhead/proprietary/qseecomd:system/bin/qseecomd \
    vendor/lge/hammerhead/proprietary/radish:system/bin/radish \
    vendor/lge/hammerhead/proprietary/rmt_storage:system/bin/rmt_storage \
    vendor/lge/hammerhead/proprietary/sensors.qcom:system/bin/sensors.qcom \
    vendor/lge/hammerhead/proprietary/subsystem_ramdump:system/bin/subsystem_ramdump \
    vendor/lge/hammerhead/proprietary/thermal-engine-hh:system/bin/thermal-engine-hh \
    vendor/lge/hammerhead/proprietary/time_daemon:system/bin/time_daemon \
    vendor/lge/hammerhead/proprietary/usbhub:system/bin/usbhub \
    vendor/lge/hammerhead/proprietary/usbhub_init:system/bin/usbhub_init \
    vendor/lge/hammerhead/proprietary/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lge/hammerhead/proprietary/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lge/hammerhead/proprietary/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lge/hammerhead/proprietary/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/lge/hammerhead/proprietary/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/lge/hammerhead/proprietary/flp.msm8974.so:system/lib/hw/flp.msm8974.so \
    vendor/lge/hammerhead/proprietary/gps.msm8974.so:system/lib/hw/gps.msm8974.so \
    vendor/lge/hammerhead/proprietary/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/lge/hammerhead/proprietary/libchromatix_imx179_common.so:system/lib/libchromatix_imx179_common.so \
    vendor/lge/hammerhead/proprietary/libchromatix_imx179_default_video.so:system/lib/libchromatix_imx179_default_video.so \
    vendor/lge/hammerhead/proprietary/libchromatix_imx179_preview.so:system/lib/libchromatix_imx179_preview.so \
    vendor/lge/hammerhead/proprietary/libchromatix_imx179_snapshot.so:system/lib/libchromatix_imx179_snapshot.so \
    vendor/lge/hammerhead/proprietary/libchromatix_mt9m114b_common.so:system/lib/libchromatix_mt9m114b_common.so \
    vendor/lge/hammerhead/proprietary/libchromatix_mt9m114b_default_video.so:system/lib/libchromatix_mt9m114b_default_video.so \
    vendor/lge/hammerhead/proprietary/libchromatix_mt9m114b_preview.so:system/lib/libchromatix_mt9m114b_preview.so \
    vendor/lge/hammerhead/proprietary/libchromatix_mt9m114b_snapshot.so:system/lib/libchromatix_mt9m114b_snapshot.so \
    vendor/lge/hammerhead/proprietary/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/lge/hammerhead/proprietary/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/lge/hammerhead/proprietary/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/lge/hammerhead/proprietary/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/lge/hammerhead/proprietary/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/lge/hammerhead/proprietary/libloc_core.so:system/lib/libloc_core.so \
    vendor/lge/hammerhead/proprietary/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/lge/hammerhead/proprietary/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_imx179.so:system/lib/libmmcamera_imx179.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_mt9m114b.so:system/lib/libmmcamera_mt9m114b.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/lge/hammerhead/proprietary/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/lge/hammerhead/proprietary/libmmQSM.so:system/lib/libmmQSM.so \
    vendor/lge/hammerhead/proprietary/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/lge/hammerhead/proprietary/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/lge/hammerhead/proprietary/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/lge/hammerhead/proprietary/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/lge/hammerhead/proprietary/libxml.so:system/lib/libxml.so \
    vendor/lge/hammerhead/proprietary/a330_pfp.fw:system/vendor/firmware/a330_pfp.fw \
    vendor/lge/hammerhead/proprietary/a330_pm4.fw:system/vendor/firmware/a330_pm4.fw \
    vendor/lge/hammerhead/proprietary/venus.b00:system/vendor/firmware/venus.b00 \
    vendor/lge/hammerhead/proprietary/venus.b01:system/vendor/firmware/venus.b01 \
    vendor/lge/hammerhead/proprietary/venus.b02:system/vendor/firmware/venus.b02 \
    vendor/lge/hammerhead/proprietary/venus.b03:system/vendor/firmware/venus.b03 \
    vendor/lge/hammerhead/proprietary/venus.b04:system/vendor/firmware/venus.b04 \
    vendor/lge/hammerhead/proprietary/venus.mdt:system/vendor/firmware/venus.mdt \
    vendor/lge/hammerhead/proprietary/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/lge/hammerhead/proprietary/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/lge/hammerhead/proprietary/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lge/hammerhead/proprietary/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lge/hammerhead/proprietary/libplayback_adreno.so:system/vendor/lib/egl/libplayback_adreno.so \
    vendor/lge/hammerhead/proprietary/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lge/hammerhead/proprietary/sensors.msm8974.so:system/vendor/lib/hw/sensors.msm8974.so \
    vendor/lge/hammerhead/proprietary/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/lge/hammerhead/proprietary/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/lge/hammerhead/proprietary/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/lge/hammerhead/proprietary/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/lge/hammerhead/proprietary/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/lge/hammerhead/proprietary/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/lge/hammerhead/proprietary/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/lge/hammerhead/proprietary/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/lge/hammerhead/proprietary/libCB.so:system/vendor/lib/libCB.so \
    vendor/lge/hammerhead/proprietary/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    vendor/lge/hammerhead/proprietary/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/lge/hammerhead/proprietary/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/lge/hammerhead/proprietary/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/lge/hammerhead/proprietary/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/lge/hammerhead/proprietary/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/lge/hammerhead/proprietary/libFuzzmmstillomxenc.so:system/vendor/lib/libFuzzmmstillomxenc.so \
    vendor/lge/hammerhead/proprietary/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/lge/hammerhead/proprietary/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/lge/hammerhead/proprietary/libidl.so:system/vendor/lib/libidl.so \
    vendor/lge/hammerhead/proprietary/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/lge/hammerhead/proprietary/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/lge/hammerhead/proprietary/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/lge/hammerhead/proprietary/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so \
    vendor/lge/hammerhead/proprietary/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/lge/hammerhead/proprietary/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/lge/hammerhead/proprietary/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/lge/hammerhead/proprietary/libmmcamera_imx179_eeprom.so:system/vendor/lib/libmmcamera_imx179_eeprom.so \
    vendor/lge/hammerhead/proprietary/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/lge/hammerhead/proprietary/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/lge/hammerhead/proprietary/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/lge/hammerhead/proprietary/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/lge/hammerhead/proprietary/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/lge/hammerhead/proprietary/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/lge/hammerhead/proprietary/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/lge/hammerhead/proprietary/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/lge/hammerhead/proprietary/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/lge/hammerhead/proprietary/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/lge/hammerhead/proprietary/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/lge/hammerhead/proprietary/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/lge/hammerhead/proprietary/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/lge/hammerhead/proprietary/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/lge/hammerhead/proprietary/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/lge/hammerhead/proprietary/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/lge/hammerhead/proprietary/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/lge/hammerhead/proprietary/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/lge/hammerhead/proprietary/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/lge/hammerhead/proprietary/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/lge/hammerhead/proprietary/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/lge/hammerhead/proprietary/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/lge/hammerhead/proprietary/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/lge/hammerhead/proprietary/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
    vendor/lge/hammerhead/proprietary/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/lge/hammerhead/proprietary/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/lge/hammerhead/proprietary/qcrilmsgtunnel.apk:system/app/qcrilmsgtunnel.apk \
    vendor/lge/hammerhead/proprietary/SprintHiddenMenu.apk:system/app/SprintHiddenMenu.apk \
    vendor/lge/hammerhead/proprietary/UpdateSetting.apk:system/app/UpdateSetting.apk \
    vendor/lge/hammerhead/proprietary/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/lge/hammerhead/proprietary/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/lge/hammerhead/proprietary/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/lge/hammerhead/proprietary/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/lge/hammerhead/proprietary/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/lge/hammerhead/proprietary/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/lge/hammerhead/proprietary/serviceitems.xml:system/etc/permissions/serviceitems.xml \
    vendor/lge/hammerhead/proprietary/qcril.db:system/etc/qcril.db \
    vendor/lge/hammerhead/proprietary/sensor_def_hh.conf:system/etc/sensor_def_hh.conf \
    vendor/lge/hammerhead/proprietary/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/lge/hammerhead/proprietary/serviceitems.jar:system/framework/serviceitems.jar \
    vendor/lge/hammerhead/proprietary/vss_init:system/vendor/bin/vss_init \
    vendor/lge/hammerhead/proprietary/bu24205_LGIT_VER_2_DATA1.bin:system/vendor/firmware/bu24205_LGIT_VER_2_DATA1.bin \
    vendor/lge/hammerhead/proprietary/bu24205_LGIT_VER_2_DATA2.bin:system/vendor/firmware/bu24205_LGIT_VER_2_DATA2.bin \
    vendor/lge/hammerhead/proprietary/bu24205_LGIT_VER_2_DATA3.bin:system/vendor/firmware/bu24205_LGIT_VER_2_DATA3.bin \
    vendor/lge/hammerhead/proprietary/bu24205_LGIT_VER_3_CAL.bin:system/vendor/firmware/bu24205_LGIT_VER_3_CAL.bin \
    vendor/lge/hammerhead/proprietary/bu24205_LGIT_VER_3_DATA1.bin:system/vendor/firmware/bu24205_LGIT_VER_3_DATA1.bin \
    vendor/lge/hammerhead/proprietary/bu24205_LGIT_VER_3_DATA2.bin:system/vendor/firmware/bu24205_LGIT_VER_3_DATA2.bin \
    vendor/lge/hammerhead/proprietary/bu24205_LGIT_VER_3_DATA3.bin:system/vendor/firmware/bu24205_LGIT_VER_3_DATA3.bin \
    vendor/lge/hammerhead/proprietary/dxhdcp2.b00:system/vendor/firmware/discretix/dxhdcp2.b00 \
    vendor/lge/hammerhead/proprietary/dxhdcp2.b01:system/vendor/firmware/discretix/dxhdcp2.b01 \
    vendor/lge/hammerhead/proprietary/dxhdcp2.b02:system/vendor/firmware/discretix/dxhdcp2.b02 \
    vendor/lge/hammerhead/proprietary/dxhdcp2.b03:system/vendor/firmware/discretix/dxhdcp2.b03 \
    vendor/lge/hammerhead/proprietary/dxhdcp2.mdt:system/vendor/firmware/discretix/dxhdcp2.mdt \
    vendor/lge/hammerhead/proprietary/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/lge/hammerhead/proprietary/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/lge/hammerhead/proprietary/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/lge/hammerhead/proprietary/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/lge/hammerhead/proprietary/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/lge/hammerhead/proprietary/libAKM8963.so:system/vendor/lib/libAKM8963.so \
    vendor/lge/hammerhead/proprietary/libDxHdcp.so:system/vendor/lib/libDxHdcp.so \
    vendor/lge/hammerhead/proprietary/libvdmengine.so:system/vendor/lib/libvdmengine.so \
    vendor/lge/hammerhead/proprietary/libvdmfumo.so:system/vendor/lib/libvdmfumo.so \
    vendor/lge/hammerhead/proprietary/libvss_common_core.so:system/vendor/lib/libvss_common_core.so \
    vendor/lge/hammerhead/proprietary/libvss_common_idl.so:system/vendor/lib/libvss_common_idl.so \
    vendor/lge/hammerhead/proprietary/libvss_common_iface.so:system/vendor/lib/libvss_common_iface.so \
    vendor/lge/hammerhead/proprietary/libvss_nv_core.so:system/vendor/lib/libvss_nv_core.so \
    vendor/lge/hammerhead/proprietary/libvss_nv_idl.so:system/vendor/lib/libvss_nv_idl.so \
    vendor/lge/hammerhead/proprietary/libvss_nv_iface.so:system/vendor/lib/libvss_nv_iface.so \
    vendor/lge/hammerhead/proprietary/bcm2079x-b5_firmware.ncd:system/vendor/firmware/bcm2079x-b5_firmware.ncd:broadcom \
    vendor/lge/hammerhead/proprietary/bcm2079x-b5_pre_firmware.ncd:system/vendor/firmware/bcm2079x-b5_pre_firmware.ncd:broadcom \
    vendor/lge/hammerhead/proprietary/bcm4335c0.hcd:system/vendor/firmware/bcm4335c0.hcd \
